"""Add stablecoin inflow ratio indicator

Revision ID: 1dedf3fec39f
Revises: e0b0161ed1a9
Create Date: 2025-10-06 15:12:00.363192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dedf3fec39f'
down_revision: Union[str, None] = 'e0b0161ed1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stablecoin_inflow_ratio_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stablecoin_inflow_ratio_indicators_id'), 'stablecoin_inflow_ratio_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stablecoin_inflow_ratio_indicators_id'), table_name='stablecoin_inflow_ratio_indicators')
    op.drop_table('stablecoin_inflow_ratio_indicators')
    # ### end Alembic commands ###
