"""Remove BitcoinExchangeInflowIndicator

Revision ID: 2bd5b97c724b
Revises: 9dd971df8179
Create Date: 2025-10-06 18:31:47.282249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bd5b97c724b'
down_revision: Union[str, None] = '9dd971df8179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bitcoin_exchange_inflow_indicators_id', table_name='bitcoin_exchange_inflow_indicators')
    op.drop_table('bitcoin_exchange_inflow_indicators')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_exchange_inflow_indicators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bitcoin_exchange_inflow_indicators_pkey')
    )
    op.create_index('ix_bitcoin_exchange_inflow_indicators_id', 'bitcoin_exchange_inflow_indicators', ['id'], unique=False)
    # ### end Alembic commands ###
