"""Add NUPL indicator

Revision ID: 4bb80bdad4ef
Revises: 1dedf3fec39f
Create Date: 2025-10-06 17:45:56.172215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb80bdad4ef'
down_revision: Union[str, None] = '1dedf3fec39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitcoin_exchange_inflow_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitcoin_exchange_inflow_indicators_id'), 'bitcoin_exchange_inflow_indicators', ['id'], unique=False)
    op.create_table('nupl_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nupl_indicators_id'), 'nupl_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nupl_indicators_id'), table_name='nupl_indicators')
    op.drop_table('nupl_indicators')
    op.drop_index(op.f('ix_bitcoin_exchange_inflow_indicators_id'), table_name='bitcoin_exchange_inflow_indicators')
    op.drop_table('bitcoin_exchange_inflow_indicators')
    # ### end Alembic commands ###
