"""Add SPOR indicator

Revision ID: 9dd971df8179
Revises: 4bb80bdad4ef
Create Date: 2025-10-06 18:04:15.319546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd971df8179'
down_revision: Union[str, None] = '4bb80bdad4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spor_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spor_indicators_id'), 'spor_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spor_indicators_id'), table_name='spor_indicators')
    op.drop_table('spor_indicators')
    # ### end Alembic commands ###
