"""Add ASOL indicator table

Revision ID: 9f9b0d6d4b09
Revises: 2bd5b97c724b
Create Date: 2025-10-09 22:20:27.024033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9b0d6d4b09'
down_revision: Union[str, None] = '2bd5b97c724b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asol_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asol_indicators_id'), 'asol_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asol_indicators_id'), table_name='asol_indicators')
    op.drop_table('asol_indicators')
    # ### end Alembic commands ###
